let mapleader=","

call plug#begin('~/.vim/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'ap/vim-css-color'
Plug 'ghifarit53/tokyonight-vim'
Plug 'jiangmiao/auto-pairs'
Plug 'kien/ctrlp.vim'
Plug 'mileszs/ack.vim'
Plug 'mustache/vim-mustache-handlebars'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'leafOfTree/vim-vue-plugin'
Plug 'sbdchd/neoformat'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'sheerun/vim-polyglot'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'w0rp/ale'
call plug#end()

inoremap jk <esc>
nnoremap <Leader>nt :NERDTreeToggle<CR>

" neovim configuration
if has('nvim')
  tnoremap <Esc> <C-\><C-n>
endif

"set cursorline
highlight ColorColumn guibg='#2b2b2b'
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1

set autoread
set background=dark
set number
set encoding=utf-8
set timeoutlen=400
set hidden
set noautochdir
set shell=/bin/zsh

"" Whitespace / Indentation
set listchars=tab:▸\ ,eol:¬,trail:·
set lcs+=space:· " show dot for whitespaces
set list
set autoindent
set expandtab                   " use spaces, not tabs (optional)
set wrap                        " wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
au FileType javascript setl sw=2 ts=2 expandtab
set backspace=indent,eol,start  " backspace through everything in insert mode
set endofline
" remove trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

"" temp file handling
set dir=/tmp/editor
set backupdir=/tmp/editor

" Some Linux distributions set filetype in /etc/vimrc.
" Clear filetype flags before changing runtimepath to force Vim to reload them.
filetype off

set complete-=i

let g:vim_markdown_folding_disabled=1
let g:airline_powerline_fonts=1

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" Neoformat config
autocmd BufWritePre *.js Neoformat
autocmd BufWritePre *.vue Neoformat
autocmd FileType vue syntax sync fromstart

let g:ctrlp_match_window=''
let g:ctrlp_working_path_mode=''
let g:ctrlp_max_files=0
let g:ctrlp_max_depth=100
let g:ctrlp_follow_symlinks=1
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.git$|tags|tmp|cache|node_modules)',
  \ 'file': '\v[\/](\.so\|\.dat|\.DS_Store)$'
  \ }

let g:mix_format_on_save = 1
let g:ale_linters = {}
let g:ale_linters['ruby'] = ['standardrb']
let g:ale_linters['javascript'] = ['eslint']
let g:ale_fixers = {'vue': ['remove_trailing_lines', 'trim_whitespace']}
let g:ale_fixers['javascript'] = ['prettier_standard']
let g:ale_fixers['ruby'] = ['standardrb']
let g:ale_linter_aliases = {'vue': ['javascript', 'html', 'scss']}
let g:ale_fix_on_save = 1
let g:ale_javascript_prettier_options = '--single-quote --trailing-comma es5'

syntax enable
syntax on
set termguicolors
let g:tokyonight_style = 'night' " available: night, storm
let g:tokyonight_enable_italic = 1
colorscheme tokyonight
set conceallevel=0

set lazyredraw
set colorcolumn=111
syntax sync minlines=256
